package com.example.it_wog.kfzfinder

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        suchen.setOnClickListener {

            var eingabeUser : String = " "
            eingabeUser = eingabefeld.text.toString()

            var kfzKennzeichen = hashMapOf(
                    "ABG" to "AltenBurG, Thüringen",
                    "ABI" to "Anhalt  BItterfeld, Sachsen-Anhalt",
                    "AC" to "AaChen, Nordrhein-Westfalen",
                    "AE" to "AuErbach, Sachsen",
                    "AH" to "AHaus, Nordrhein-Westfalen",
                    "AIB" to "AIBling, Bayern",
                    "AIC" to "AIChach, Bayern",
                    "AK" to "AltenKirchen, Rheinland-Pfalz",
                    "ALF" to "ALFeld, Niedersachsen",
                    "ALZ" to "ALZenau, Bayern",
                    "AM" to "AMberg, Bayern",
                    "AN" to "ANsbach, Bayern",
                    "ANA" to "ANnAberg, Sachsen",
                    "ANG" to "ANGermünde, Brandenburg",
                    "ANK" to "ANKlam, Mecklenburg-Vorpommern",
                    "AÖ" to "AltÖtting, Bayern",
                    "AP" to "APolda, Thüringen",
                    "APD" to "APolDa, Thüringen",
                    "ARN" to "ARNstadt, Thüringen",
                    "ART" to "ARTern, Thüringen",
                    "AS" to "Amberg  Sulzbach, Bayern",
                    "ASL" to "ASchersLeben, Sachsen-Anhalt",
                    "ASZ" to "Aue  SchwarZenberg, Sachsen",
                    "AT" to "AltenTreptow, Mecklenburg-Vorpommern",
                    "AU" to "AUe, Sachsen",
                    "AUR" to "AURich, Niedersachsen",
                    "AW" to "AhrWeiler, Rheinland-Pfalz",
                    "AZ" to "AlZey, Rheinland-Pfalz",
                    "AZE" to "Anhalt-ZErbst, Sachsen-Anhalt",
                    "B" to "Berlin, Berlin",
                    "BA" to "BAmberg, Bayern",
                    "BAD" to "BADen-Baden, Baden-Württemberg",
                    "BAR" to "BARnim, Brandenburg",
                    "BB" to "BöBlingen, Baden-Württemberg",
                    "BBG" to "BernBurG, Sachsen-Anhalt",
                    "BBL" to "BrandenBurgische Landesregierung, Brandenburg",
                    "BC" to "BiberaCh, Baden-Württemberg",
                    "BCH" to "BuCHen, Baden-Württemberg",
                    "BD" to "BunD, bundesweit",
                    "BE" to "Beckum, Nordrhein-Westfalen",
                    "BED" to "Brand-ErbisDorf, Sachsen",
                    "BER" to "BERnau, Brandenburg",
                    "BF" to "BurgsteinFurt, Nordrhein-Westfalen",
                    "BGD" to "BerchtesGaDen, Bayern",
                    "BGL" to "BerchtesGadener Land, Bayern",
                    "BH" to "BüHl, Baden-Württemberg",
                    "BI" to "BIelefeld, Nordrhein-Westfalen",
                    "BID" to "BIeDenkopf, Hessen",
                    "BIN" to "BINgen, Rheinland-Pfalz",
                    "BIR" to "BIRkenfeld, Rheinland-Pfalz",
                    "BIT" to "BITburg, Rheinland-Pfalz",
                    "BIW" to "BIschofsWerda, Sachsen",
                    "BK" to "BacKnang, Baden-Württemberg",
                    "BKS" to "BernKaStel, Rheinland-Pfalz",
                    "BL" to "BaLingen, Baden-Württemberg",
                    "BLB" to "BerLeBurg, Nordrhein-Westfalen",
                    "BLK" to "BurgenLandKreis, Sachsen-Anhalt",
                    "BM" to "BergheiM, Nordrhein-Westfalen",
                    "BN" to "BonN, Nordrhein-Westfalen",
                    "BNA" to "BorNA, Sachsen",
                    "BO" to "BOchum, Nordrhein-Westfalen",
                    "BÖ" to "BÖrde, Sachsen-Anhalt",
                    "BOH" to "BOcHolt, Nordrhein-Westfalen",
                    "BOR" to "BORken, Nordrhein-Westfalen",
                    "BOT" to "BOTtrop, Nordrhein-Westfalen",
                    "BP" to "BundesPolizei, bundesweit",
                    "BRA" to "BRAke, Niedersachsen",
                    "BRB" to "BRandenBurg, Brandenburg",
                    "BRG" to "BuRG, Sachsen-Anhalt",
                    "BRK" to "BRücKenau, Bayern",
                    "BRL" to "BRaunLage, Niedersachsen",
                    "BRV" to "BRemerVörde, Niedersachsen",
                    "BS" to "BraunSchweig, Niedersachsen",
                    "BSK" to "BeeSKow, Brandenburg",
                    "BT" to "BayreuTh, Bayern",
                    "BTF" to "BitTerFeld, Sachsen-Anhalt",
                    "BÜD" to "BÜDingen, Hessen",
                    "BUL" to "BUrgLengenfeld, Bayern",
                    "BÜR" to "BÜRen, Nordrhein-Westfalen",
                    "BÜS" to "BÜSingen, Baden-Württemberg",
                    "BÜZ" to "BÜtZow, Mecklenburg-Vorpommern",
                    "BW" to "Bundes-Wasserstraßen- und Schifffahrtsverwaltung, bundesweit",
                    "BWL" to "Baden-Württembergischer Landtag, Baden-Württemberg",
                    "BYL" to "BaYerischer Landtag, Bayern",
                    "BZ" to "BautZen, Sachsen",
                    "C" to "Chemnitz, Sachsen",
                    "CA" to "CAlau, Brandenburg",
                    "CAS" to "CAStrop, Nordrhein-Westfalen",
                    "CB" to "CottBus, Brandenburg",
                    "CE" to "CElle, Niedersachsen",
                    "CHA" to "CHAm, Bayern",
                    "CLP" to "CLopPenburg, Niedersachsen",
                    "CLZ" to "CLausthal-Zellerfeld, Niedersachsen",
                    "CO" to "COburg, Bayern",
                    "COC" to "COChem, Rheinland-Pfalz",
                    "COE" to "COEsfeld, Nordrhein-Westfalen",
                    "CR" to "CRailsheim, Baden-Württemberg",
                    "CUX" to "CUXhaven, Niedersachsen",
                    "CW" to "CalW, Baden-Württemberg",
                    "D" to "Düsseldorf, Nordrhein-Westfalen",
                    "DA" to "DArmstadt, Hessen",
                    "DAH" to "DAcHau, Bayern",
                    "DAN" to "DANnenberg, Niedersachsen",
                    "DAU" to "DAUn, Rheinland-Pfalz",
                    "DBR" to "DoBeRan, Mecklenburg-Vorpommern",
                    "DD" to "DresDen, Sachsen",
                    "DE" to "DEssau, Sachsen-Anhalt",
                    "DEG" to "DEGgendorf, Bayern",
                    "DEL" to "DELmenhorst, Niedersachsen",
                    "DGF" to "DinGolFing, Bayern",
                    "DH" to "DiepHolz, Niedersachsen",
                    "DI" to "DIeburg, Hessen",
                    "DIL" to "DILlenburg, Hessen",
                    "DIN" to "DINslaken, Nordrhein-Westfalen",
                    "DIZ" to "DIeZ, Rheinland-Pfalz",
                    "DKB" to "DinKelsBühl, Bayern",
                    "DL" to "DöbeLn, Sachsen",
                    "DLG" to "DilLinGen, Bayern",
                    "DM" to "DemMin, Mecklenburg-Vorpommern",
                    "DN" to "DüreN, Nordrhein-Westfalen",
                    "DO" to "DOrtmund, Nordrhein-Westfalen",
                    "DON" to "DONauwörth, Bayern",
                    "DU" to "DUisburg, Nordrhein-Westfalen",
                    "DUD" to "DUDerstadt, Niedersachsen",
                    "DÜW" to "DÜrkheim an der Weinstraße, Rheinland-Pfalz",
                    "DW" to "DippoldisWalde, Sachsen",
                    "DZ" to "DelitZsch, Sachsen",
                    "E" to "Essen, Nordrhein-Westfalen",
                    "EA" to "EisenAch, Thüringen",
                    "EB" to "EilenBurg, Sachsen",
                    "EBE" to "EBErsberg, Bayern",
                    "EBN" to "EBerN, Bayern",
                    "EBS" to "EBermannStadt, Bayern",
                    "ECK" to "ECKernförde, Schleswig-Holstein",
                    "ED" to "ErDing, Bayern",
                    "EE" to "Elbe  Elster, Brandenburg",
                    "EF" to "ErFurt, Thüringen",
                    "EG" to "EGgenfelden, Bayern",
                    "EH" to "EisenHüttenstadt, Brandenburg",
                    "EI" to "EIchstätt, Bayern",
                    "EIC" to "EIChsfeld, Thüringen",
                    "EIL" to "EIsLeben, Sachsen-Anhalt",
                    "EIN" to "EINbeck, Niedersachsen",
                    "EIS" to "EISenberg, Thüringen",
                    "EL" to "EmsLand, Niedersachsen",
                    "EM" to "EMmendingen, Baden-Württemberg",
                    "EMD" to "EMDen, Niedersachsen",
                    "EMS" to "EMS, Rheinland-Pfalz",
                    "EN" to "ENnepe, Nordrhein-Westfalen",
                    "ER" to "ERlangen, Bayern",
                    "ERB" to "ERBach, Hessen",
                    "ERH" to "ERlangen  Höchstadt, Bayern",
                    "ERK" to "ERKelenz, Nordrhein-Westfalen",
                    "ERZ" to "ERZgebirge, Sachsen",
                    "ES" to "ESslingen, Baden-Württemberg",
                    "ESB" to "ESchenBach, Bayern",
                    "ESW" to "ESchWege, Hessen",
                    "EU" to "EUskirchen, Nordrhein-Westfalen",
                    "EW" to "EbersWalde, Brandenburg",
                    "F" to "Frankfurt, Hessen",
                    "FB" to "FriedBerg, Hessen",
                    "FD" to "FulDa, Hessen",
                    "FDB" to "FrieDBerg, Bayern",
                    "FDS" to "FreuDenStadt, Baden-Württemberg",
                    "FEU" to "FEUchtwangen, Bayern",
                    "FF" to "FrankFurt, Brandenburg",
                    "FFB" to "FürstenFeldBruck, Bayern",
                    "FG" to "FreiberG, Sachsen",
                    "FI" to "FInsterwalde, Brandenburg",
                    "FKB" to "FranKenBerg, Hessen",
                    "FL" to "FLensburg, Schleswig-Holstein",
                    "FLÖ" to "FLÖha, Sachsen",
                    "FN" to "FriedrichshafeN, Baden-Württemberg",
                    "FO" to "FOrchheim, Bayern",
                    "FOR" to "FORst, Brandenburg",
                    "FR" to "FReiburg, Baden-Württemberg",
                    "FRG" to "FReyung  Grafenau, Bayern",
                    "FRI" to "FRIesland, Niedersachsen",
                    "FRW" to "FReienWalde, Brandenburg",
                    "FS" to "FreiSing, Bayern",
                    "FT" to "FrankenThal, Rheinland-Pfalz",
                    "FTL" to "FreiTaL, Sachsen",
                    "FÜ" to "FÜrth, Bayern",
                    "FÜS" to "FÜSsen, Bayern",
                    "FW" to "FürstenWalde, Brandenburg",
                    "FZ" to "FritZlar, Hessen",
                    "G" to "Gera, Thüringen",
                    "GA" to "GArdelegen, Sachsen-Anhalt",
                    "GAN" to "GANdersheim, Niedersachsen",
                    "GAP" to "GArmisch-Partenkirchen, Bayern",
                    "GC" to "GlauChau, Sachsen",
                    "GD" to "GmünD, Baden-Württemberg",
                    "GDB" to "GaDeBusch, Mecklenburg-Vorpommern",
                    "GE" to "GElsenkirchen, Nordrhein-Westfalen",
                    "GEL" to "GELdern, Nordrhein-Westfalen",
                    "GEO" to "GErOlzhofen, Bayern",
                    "" to ", ",
                    "GER" to "GERmersheim, Rheinland-Pfalz",
                    "GF" to "GiFhorn, Niedersachsen",
                    "GG" to "Groß-Gerau, Hessen",
                    "GHA" to "GeitHAin, Sachsen",
                    "GHC" to "GräfenHainiChen, Sachsen-Anhalt",
                    "GI" to "GIeßen, Hessen",
                    "GK" to "GeilenKirchen, Nordrhein-Westfalen",
                    "GL" to "GLadbach, Nordrhein-Westfalen",
                    "GLA" to "GLAdbeck, Nordrhein-Westfalen",
                    "GM" to "GumMersbach, Nordrhein-Westfalen",
                    "GMN" to "GrimMeN, Mecklenburg-Vorpommern",
                    "GN" to "GelnhauseN, Hessen",
                    "GNT" to "GeNThin, Sachsen-Anhalt",
                    "GÖ" to "GÖttingen, Niedersachsen",
                    "GOA" to "GOAr, Rheinland-Pfalz",
                    "GOH" to "GOarsHausen, Rheinland-Pfalz",
                    "GP" to "GöpPingen, Baden-Württemberg",
                    "GR" to "GöRlitz, Sachsen",
                    "GRA" to "GRAfenau, Bayern",
                    "GRH" to "GRoßenHain, Sachsen",
                    "GRI" to "GRIesbach, Bayern",
                    "GRM" to "GRimMa, Sachsen",
                    "GRZ" to "GReiZ, Thüringen",
                    "GS" to "GoSlar, Niedersachsen",
                    "GT" to "GüTersloh, Nordrhein-Westfalen",
                    "GTH" to "GoTHa, Thüringen",
                    "GÜ" to "GÜstrow, Mecklenburg-Vorpommern",
                    "GUB" to "GUBen, Brandenburg",
                    "GUN" to "GUNzenhausen, Bayern",
                    "GV" to "GreVenbroich, Nordrhein-Westfalen",
                    "GVM" to "GreVesMühlen, Mecklenburg-Vorpommern",
                    "GW" to "GreifsWald, Mecklenburg-Vorpommern",
                    "GZ" to "GünZburg, Bayern",
                    "H" to "Hannover, Niedersachsen",
                    "HA" to "HAgen, Nordrhein-Westfalen",
                    "HAB" to "HAmmelBurg, Bayern",
                    "HAL" to "HALle, Sachsen-Anhalt",
                    "HAM" to "HAMm, Nordrhein-Westfalen",
                    "HAS" to "HASsfurt, Bayern",
                    "HB" to "Hansestadt Bremen, Bremen",
                    "HBN" to "HildBurghauseN, Thüringen",
                    "HBS" to "HalBerStadt, Sachsen-Anhalt",
                    "HC" to "HainiChen, Sachsen",
                    "HCH" to "HeCHingen, Baden-Württemberg",
                    "HD" to "HeiDelberg, Baden-Württemberg",
                    "HDH" to "HeiDenHeim, Baden-Württemberg",
                    "HDL" to "HalDensLeben, Sachsen-Anhalt",
                    "HE" to "HElmstedt, Niedersachsen",
                    "HEB" to "HErsBruck, Bayern",
                    "HEF" to "HErsFeld, Hessen",
                    "HEI" to "HEIde, Schleswig-Holstein",
                    "HEL" to "HEssischer Landtag, Hessen",
                    "HER" to "HERne, Nordrhein-Westfalen",
                    "HET" to "HETtstedt, Sachsen-Anhalt",
                    "HF" to "HerFord, Nordrhein-Westfalen",
                    "HG" to "HomburG, Hessen",
                    "HGN" to "HaGeNow, Mecklenburg-Vorpommern",
                    "HGW" to "Hansestadt GreifsWald, Mecklenburg-Vorpommern",
                    "HH" to "Hansestadt Hamburg, Hamburg",
                    "HHM" to "HoHenMölsen, Sachsen-Anhalt",
                    "HI" to "HIldesheim, Niedersachsen",
                    "HIG" to "HeilIGenstadt, Thüringen",
                    "HIP" to "HIlPoltstein, Bayern",
                    "HK" to "HeideKreis, Niedersachsen",
                    "HL" to "Hansestadt Lübeck, Schleswig-Holstein",
                    "HM" to "HaMeln, Niedersachsen",
                    "HMÜ" to "Hann. MÜnden, Niedersachsen",
                    "HN" to "HeilbronN, Baden-Württemberg",
                    "HO" to "HOf, Bayern",
                    "HOG" to "HOfGeismar, Hessen",
                    "HOH" to "HOfHeim, Bayern",
                    "HOL" to "HOLzminden, Niedersachsen",
                    "HOM" to "HOMburg, Saarland",
                    "HOR" to "HORb, Baden-Württemberg",
                    "HÖS" to "HÖchStadt, Bayern",
                    "HOT" to "HOhensTein, Sachsen",
                    "HP" to "HepPenheim, Hessen",
                    "HR" to "HombeRg, Hessen",
                    "HRO" to "Hansestadt ROstock, Mecklenburg-Vorpommern",
                    "HS" to "HeinSberg, Nordrhein-Westfalen",
                    "HSK" to "HochSauerlandKreis, Nordrhein-Westfalen",
                    "HST" to "Hansestadt STralsund, Mecklenburg-Vorpommern",
                    "HU" to "HanaU, Hessen",
                    "HV" to "HaVelberg, Sachsen-Anhalt",
                    "HVL" to "HaVelLand, Brandenburg",
                    "HWI" to "Hansestadt WIsmar, Mecklenburg-Vorpommern",
                    "HX" to "HöXter, Nordrhein-Westfalen",
                    "HY" to "HoYerswerda, Sachsen",
                    "HZ" to "HarZ, Sachsen-Anhalt",
                    "" to ", ",
                    "IGB" to "InGBert, Saarland",
                    "IK" to "Ilm-Kreis, Thüringen",
                    "IL" to "ILmenau, Thüringen",
                    "ILL" to "ILLertissen, Bayern",
                    "IN" to "INgolstadt, Bayern",
                    "IZ" to "ItZehoe, Schleswig-Holstein",
                    "J" to "Jena, Thüringen",
                    "JE" to "JEssen, Sachsen-Anhalt",
                    "JL" to "Jerichower Land, Sachsen-Anhalt",
                    "JÜL" to "JÜLich, Nordrhein-Westfalen",
                    "K" to "Köln, Nordrhein-Westfalen",
                    "KA" to "KArlsruhe, Baden-Württemberg",
                    "KB" to "KorBach, Hessen",
                    "KC" to "KronaCh, Bayern",
                    "KE" to "KEmpten, Bayern",
                    "" to ", ",
                    "KEH" to "KElHeim, Bayern",
                    "KEL" to "KEhL, Baden-Württemberg",
                    "KEM" to "KEMnath, Bayern",
                    "KF" to "KauFbeuren, Bayern",
                    "KG" to "KissinGen, Bayern",
                    "KH" to "KreuznacH, Rheinland-Pfalz",
                    "KI" to "KIel, Schleswig-Holstein",
                    "KIB" to "KIrchheimBolanden, Rheinland-Pfalz",
                    "KK" to "Kempen  Krefeld, Nordrhein-Westfalen",
                    "KL" to "KaisersLautern, Rheinland-Pfalz",
                    "KLE" to "KLEve, Nordrhein-Westfalen",
                    "KLZ" to "KLötZe, Sachsen-Anhalt",
                    "KM" to "KaMenz, Sachsen",
                    "KN" to "KoNstanz, Baden-Württemberg",
                    "KO" to "KOblenz, Rheinland-Pfalz",
                    "KÖN" to "KÖNigshofen, Bayern",
                    "KÖT" to "KÖThen, Sachsen-Anhalt",
                    "KÖZ" to "KÖtZting, Bayern",
                    "KR" to "KRefeld, Nordrhein-Westfalen",
                    "KRU" to "KRUmbach, Bayern",
                    "KS" to "KasSel, Hessen",
                    "KT" to "KiTzingen, Bayern",
                    "KU" to "KUlmbach, Bayern",
                    "KÜN" to "KÜNzelsau, Baden-Württemberg",
                    "KUS" to "KUSel, Rheinland-Pfalz",
                    "KW" to "Königs Wusterhausen, Brandenburg",
                    "KY" to "KYritz, Brandenburg",
                    "KYF" to "KYFfhäuser, Thüringen",
                    "L" to "Leipzig, Sachsen",
                    "LA" to "LAndshut, Bayern",
                    "LAN" to "LANdau, Bayern",
                    "LAU" to "LAUf, Bayern",
                    "LB" to "LudwigsBurg, Baden-Württemberg",
                    "LBS" to "LoBenStein, Thüringen",
                    "LBZ" to "LüBZ, Mecklenburg-Vorpommern",
                    "LC" to "LuCkau, Brandenburg",
                    "LD" to "LanDau, Rheinland-Pfalz",
                    "LDK" to "Lahn-Dill-Kreis, Hessen",
                    "LDS" to "Landkreis Dahme-Spreewald, Brandenburg",
                    "LEO" to "LEOnberg, Baden-Württemberg",
                    "LER" to "LEeR, Niedersachsen",
                    "LEV" to "LEVerkusen, Nordrhein-Westfalen",
                    "LF" to "LauFen, Bayern",
                    "LG" to "LüneburG, Niedersachsen",
                    "LH" to "LüdingHausen, Nordrhein-Westfalen",
                    "LI" to "LIndau, Bayern",
                    "LIB" to "LIeBenwerda, Brandenburg",
                    "LIF" to "LIchtenFels, Bayern",
                    "LIP" to "LIPpe, Nordrhein-Westfalen",
                    "LL" to "Landsberg am Lech, Bayern",
                    "LM" to "LiMburg, Hessen",
                    "LN" to "LübbeN, Brandenburg",
                    "LÖ" to "LÖrrach, Baden-Württemberg",
                    "LÖB" to "LÖBau, Sachsen",
                    "LOS" to "Landkreis Oder-Spree, Brandenburg",
                    "LP" to "LiPpstadt, Nordrhein-Westfalen",
                    "LR" to "LahR, Baden-Württemberg",
                    "LRO" to "Landkreis ROstock, Mecklenburg-Vorpommern",
                    "LSA" to "Land Sachsen-Anhalt, Sachsen-Anhalt",
                    "LSN" to "Landtag SachseN, Sachsen",
                    "LSZ" to "LangenSalZa, Thüringen",
                    "LU" to "LUdwigshafen, Rheinland-Pfalz",
                    "LÜN" to "LÜNen, Nordrhein-Westfalen",
                    "LUP" to "LUdwigslust  Parchim, Mecklenburg-Vorpommern",
                    "LWL" to "LudWigsLust, Mecklenburg-Vorpommern",
                    "M" to "München, Bayern",
                    "MA" to "MAnnheim, Baden-Württemberg",
                    "MAB" to "MArienBerg, Sachsen",
                    "MAI" to "MAInburg, Bayern",
                    "MAK" to "MArKtredwitz, Bayern",
                    "MAL" to "MALlersdorf, Bayern",
                    "MB" to "MiesBach, Bayern",
                    "MC" to "MalChin, Mecklenburg-Vorpommern",
                    "MD" to "MagDeburg, Sachsen-Anhalt",
                    "ME" to "MEttmann, Nordrhein-Westfalen",
                    "MED" to "MElDorf, Schleswig-Holstein",
                    "MEG" to "MElsunGen, Hessen",
                    "MEI" to "MEIßen, Sachsen",
                    "MEK" to "Mittlerer ErzgebirgsKreis, Sachsen",
                    "MER" to "MERseburg, Sachsen-Anhalt",
                    "MET" to "MEllrichstadT, Bayern",
                    "MG" to "MönchenGladbach, Nordrhein-Westfalen",
                    "MGH" to "MerGentHeim, Baden-Württemberg",
                    "MGN" to "MeininGeN, Thüringen",
                    "MH" to "MülHeim, Nordrhein-Westfalen",
                    "MHL" to "MüHLhausen, Thüringen",
                    "MI" to "MInden, Nordrhein-Westfalen",
                    "MIL" to "MILtenberg, Bayern",
                    "MK" to "Märkischer Kreis, Nordrhein-Westfalen",
                    "MKK" to "Main-Kinzig-Kreis, Hessen",
                    "ML" to "Mansfelder Land, Sachsen-Anhalt",
                    "MM" to "MemMingen, Bayern",
                    "MN" to "MiNdelheim, Bayern",
                    "MO" to "MOers, Nordrhein-Westfalen",
                    "MOD" to "MarktOberDorf, Bayern",
                    "MOL" to "Märkisch-OderLand, Brandenburg",
                    "MON" to "MONschau, Nordrhein-Westfalen",
                    "MOS" to "MOSbach, Baden-Württemberg",
                    "MQ" to "Merseburg  Querfurt, Sachsen-Anhalt",
                    "MR" to "MaRburg, Hessen",
                    "MS" to "MünSter, Nordrhein-Westfalen",
                    "MSE" to "Mecklenburgische SEenplatte, Mecklenburg-Vorpommern",
                    "MSH" to "Mansfeld  SüdHarz, Sachsen-Anhalt",
                    "MSP" to "Main  SPessart, Bayern",
                    "MST" to "Mecklenburg-STrelitz, Mecklenburg-Vorpommern",
                    "MTK" to "Main-Taunus-Kreis, Hessen",
                    "MTL" to "MuldenTaL, Sachsen",
                    "MÜ" to "MÜhldorf, Bayern",
                    "MÜB" to "MÜnchBerg, Bayern",
                    "MÜR" to "MÜRitz, Mecklenburg-Vorpommern",
                    "MVL" to "Mecklenburg-Vorpommerscher Landtag, Mecklenburg-Vorpommern",
                    "MW" to "MittWeida, Sachsen",
                    "MY" to "MaYen, Rheinland-Pfalz",
                    "MYK" to "MaYen  Koblenz, Rheinland-Pfalz",
                    "MZ" to "MainZ, Rheinland-Pfalz",
                    "MZG" to "MerZiG, Saarland",
                    "N" to "Nürnberg, Bayern",
                    "NAB" to "NABburg, Bayern",
                    "NAI" to "NAIla, Bayern",
                    "NAU" to "NAUen, Brandenburg",
                    "NB" to "NeuBrandenburg, Mecklenburg-Vorpommern",
                    "ND" to "Neuburg an der Donau, Bayern",
                    "NDH" to "NorDHausen, Thüringen",
                    "NE" to "NEuss, Nordrhein-Westfalen",
                    "NEA" to "NEustadt an der Aisch, Bayern",
                    "NEB" to "NEBra, Sachsen-Anhalt",
                    "NEC" to "NEustadt bei Coburg, Bayern",
                    "NEN" to "NEuNburg, Bayern",
                    "NES" to "NEustadt an der Saale, Bayern",
                    "NEW" to "NEustadt an der Waldnaab, Bayern",
                    "NF" to "NordFriesland, Schleswig-Holstein",
                    "NH" to "NeuHaus, Thüringen",
                    "NI" to "NIenburg, Niedersachsen",
                    "NK" to "NeunKirchen, Saarland",
                    "NL" to "Niedersächsischer Landtag, Niedersachsen",
                    "NM" to "NeuMarkt, Bayern",
                    "NMB" to "NauMBurg, Sachsen-Anhalt",
                    "NMS" to "NeuMünSter, Schleswig-Holstein",
                    "NÖ" to "NÖrdlingen, Bayern",
                    "NOH" to "NOrdHorn, Niedersachsen",
                    "NOL" to "Niederschlesische OberLausitz, Sachsen",
                    "NOM" to "NOrtheiM, Niedersachsen",
                    "NOR" to "NORden, Niedersachsen",
                    "NP" to "NeurupPin, Brandenburg",
                    "NR" to "Neuwied am Rhein, Rheinland-Pfalz",
                    "NRW" to "NordRhein-Westfalen, Nordrhein-Westfalen",
                    "NT" to "NürTingen, Baden-Württemberg",
                    "NU" to "Neu-Ulm, Bayern",
                    "NVP" to "NordVorPommern, Mecklenburg-Vorpommern",
                    "NW" to "Neustadt an der Weinstraße, Rheinland-Pfalz",
                    "NWM" to "NordWestMecklenburg, Mecklenburg-Vorpommern",
                    "NY" to "NieskY, Sachsen",
                    "NZ" to "NeustrelitZ, Mecklenburg-Vorpommern",
                    "OA" to "OberAllgäu, Bayern",
                    "OAL" to "OstALlgäu, Bayern",
                    "OB" to "OBerhausen, Nordrhein-Westfalen",
                    "OBG" to "OsterBurG, Sachsen-Anhalt",
                    "OC" to "OsChersleben, Sachsen-Anhalt",
                    "OCH" to "OCHsenfurt, Bayern",
                    "OD" to "OlDesloe, Schleswig-Holstein",
                    "OE" to "OlpE, Nordrhein-Westfalen",
                    "OF" to "OFfenbach, Hessen",
                    "OG" to "OffenburG, Baden-Württemberg",
                    "OH" to "OstHolstein, Schleswig-Holstein",
                    "OHA" to "Osterode am HArz, Niedersachsen",
                    "ÖHR" to "ÖHRingen, Baden-Württemberg",
                    "OHV" to "OberHaVel, Brandenburg",
                    "OHZ" to "OsterHolZ, Niedersachsen",
                    "OK" to "OhreKreis, Sachsen-Anhalt",
                    "OL" to "OLdenburg, Niedersachsen",
                    "OP" to "OPladen, Nordrhein-Westfalen",
                    "OPR" to "OstPrignitz  Ruppin, Brandenburg",
                    "OS" to "OSnabrück, Niedersachsen",
                    "OSL" to "OberSpreewald  Lausitz, Brandenburg",
                    "OVI" to "OberVIechtach, Bayern",
                    "OVL" to "OberVogtLand, Sachsen",
                    "OZ" to "OschatZ, Sachsen",
                    "P" to "Potsdam, Brandenburg",
                    "PA" to "PAssau, Bayern",
                    "PAF" to "PfAFfenhofen, Bayern",
                    "PAN" to "PfArrkircheN, Bayern",
                    "PAR" to "PARsberg, Bayern",
                    "PB" to "PaderBorn, Nordrhein-Westfalen",
                    "PCH" to "ParCHim, Mecklenburg-Vorpommern",
                    "PE" to "PEine, Niedersachsen",
                    "PEG" to "PEGnitz, Bayern",
                    "PF" to "PForzheim, Baden-Württemberg",
                    "PI" to "PInneberg, Schleswig-Holstein",
                    "PIR" to "PIRna, Sachsen",
                    "PL" to "PLauen, Sachsen",
                    "PLÖ" to "PLÖn, Schleswig-Holstein",
                    "PM" to "Potsdam  Mittelmark, Brandenburg",
                    "PN" to "PößNeck, Thüringen",
                    "PR" to "PRignitz, Brandenburg",
                    "PRÜ" to "PRÜm, Rheinland-Pfalz",
                    "PS" to "PirmaSens, Rheinland-Pfalz",
                    "PW" to "PaseWalk, Mecklenburg-Vorpommern",
                    "PZ" to "PrenZlau, Brandenburg",
                    "QFT" to "QuerFurT, Sachsen-Anhalt",
                    "QLB" to "QuedLinBurg, Sachsen-Anhalt",
                    "R" to "Regensburg, Bayern",
                    "RA" to "RAstatt, Baden-Württemberg",
                    "RC" to "ReiChenbach, Sachsen",
                    "RD" to "RenDsburg, Schleswig-Holstein",
                    "RDG" to "Ribnitz-DamGarten, Mecklenburg-Vorpommern",
                    "RE" to "REcklinghausen, Nordrhein-Westfalen",
                    "REG" to "REGen, Bayern",
                    "REH" to "REHau, Bayern",
                    "REI" to "REIchenhall, Bayern",
                    "RG" to "Riesa  Großenhain, Sachsen",
                    "RH" to "RotH, Bayern",
                    "RI" to "RInteln, Niedersachsen",
                    "RID" to "RIeDenburg, Bayern",
                    "RIE" to "RIEsa, Sachsen",
                    "RL" to "RochLitz, Sachsen",
                    "RM" to "Röbel/Müritz, Mecklenburg-Vorpommern",
                    "RN" to "RatheNow, Brandenburg",
                    "RO" to "ROsenheim, Bayern",
                    "ROD" to "RODing, Bayern",
                    "ROF" to "ROtenburg an der Fulda, Hessen",
                    "ROK" to "ROcKenhausen, Rheinland-Pfalz",
                    "ROL" to "ROttenburg an der Laaber, Bayern",
                    "ROS" to "ROStock, Mecklenburg-Vorpommern",
                    "ROT" to "ROthenburg ob der Tauber, Bayern",
                    "ROW" to "ROtenburg (Wümme), Niedersachsen",
                    "RP" to "Rhein-Pfalz, Rheinland-Pfalz",
                    "RPL" to "Rheinland-Pfälzischer Landtag, Rheinland-Pfalz",
                    "RS" to "RemScheid, Nordrhein-Westfalen",
                    "RSL" to "RosSLau, Sachsen-Anhalt",
                    "RT" to "ReuTlingen, Baden-Württemberg",
                    "RU" to "RUdolstadt, Thüringen",
                    "RÜD" to "RÜDesheim, Hessen",
                    "RÜG" to "RÜGen, Mecklenburg-Vorpommern",
                    "RV" to "RaVensburg, Baden-Württemberg",
                    "RW" to "RottWeil, Baden-Württemberg",
                    "RZ" to "RatZeburg, Schleswig-Holstein",
                    "S" to "Stuttgart, Baden-Württemberg",
                    "SAB" to "SAarBurg, Rheinland-Pfalz",
                    "SAD" to "SchwAnDorf, Bayern",
                    "SAL" to "SAarländischer Landtag, Saarland",
                    "SAN" to "StAdtsteiNach, Bayern",
                    "SAW" to "SAlzWedel, Sachsen-Anhalt",
                    "SB" to "SaarBrücken, Saarland",
                    "SBG" to "StrasBurG, Mecklenburg-Vorpommern",
                    "SBK" to "SchöneBecK, Sachsen-Anhalt",
                    "SC" to "SChwabach, Bayern",
                    "SCZ" to "SChleiZ, Thüringen",
                    "SDH" to "SonDersHausen, Thüringen",
                    "SDL" to "StenDaL, Sachsen-Anhalt",
                    "SDT" to "SchweDT, Brandenburg",
                    "SE" to "SEgeberg, Schleswig-Holstein",
                    "SEB" to "SEBnitz, Sachsen",
                    "SEE" to "SEElow, Brandenburg",
                    "SEF" to "SchEinFeld, Bayern",
                    "SEL" to "SELb, Bayern",
                    "SFB" to "SenFtenBerg, Brandenburg",
                    "SFT" to "StaßFurT, Sachsen-Anhalt",
                    "SG" to "SolinGen, Nordrhein-Westfalen",
                    "SGH" to "SanGerHausen, Sachsen-Anhalt",
                    "SH" to "Schleswig-Holstein, Schleswig-Holstein",
                    "SHA" to "Schwäbisch HAll, Baden-Württemberg",
                    "SHG" to "StadtHaGen, Niedersachsen",
                    "SHK" to "Saale-Holzland-Kreis, Thüringen",
                    "SHL" to "SuHL, Thüringen",
                    "SI" to "SIegen, Nordrhein-Westfalen",
                    "SIG" to "SIGmaringen, Baden-Württemberg",
                    "SIM" to "SIMmern, Rheinland-Pfalz",
                    "SK" to "SaaleKreis, Sachsen-Anhalt",
                    "SL" to "SchLeswig, Schleswig-Holstein",
                    "SLE" to "SchLEiden, Nordrhein-Westfalen",
                    "SLF" to "SaaLFeld, Thüringen",
                    "SLK" to "SalzLandKreis, Sachsen-Anhalt",
                    "SLN" to "SchmölLN, Thüringen",
                    "SLS" to "SaarLouiS, Saarland",
                    "SLÜ" to "SchLÜchtern, Hessen",
                    "SLZ" to "SaLZungen, Thüringen",
                    "SM" to "SchMmalkalden, Thüringen",
                    "SMÜ" to "SchwabMÜnchen, Bayern",
                    "SN" to "SchweriN, Mecklenburg-Vorpommern",
                    "SO" to "SOest, Nordrhein-Westfalen",
                    "SOB" to "SchrOBenhausen, Bayern",
                    "SOG" to "SchOnGau, Bayern",
                    "SOK" to "Saale-Orla-Kreis, Thüringen",
                    "SÖM" to "SÖMmerda, Thüringen",
                    "SON" to "SONneberg, Thüringen",
                    "SP" to "SPeyer, Rheinland-Pfalz",
                    "SPB" to "SPremBerg, Brandenburg",
                    "SPN" to "SPree  Neiße, Brandenburg",
                    "SR" to "StRaubing, Bayern",
                    "SRB" to "StRausBerg, Brandenburg",
                    "SRO" to "StadtROda, Thüringen",
                    "ST" to "STeinfurt, Nordrhein-Westfalen",
                    "STA" to "STArnberg, Bayern",
                    "STB" to "STernBerg, Mecklenburg-Vorpommern",
                    "STD" to "STaDe, Niedersachsen",
                    "STE" to "STaffelstEin, Bayern",
                    "STL" to "STolLberg, Sachsen",
                    "SU" to "SiegbUrg, Nordrhein-Westfalen",
                    "SUL" to "SULzbach, Bayern",
                    "SÜW" to "SÜdliche Weinstraße, Rheinland-Pfalz",
                    "SW" to "SchWeinfurt, Bayern",
                    "SWA" to "SchWAlbach, Hessen",
                    "SZ" to "SalZgitter, Niedersachsen",
                    "SZB" to "SchwarZenBerg, Sachsen",
                    "TBB" to "TauBerBischofsheim, Baden-Württemberg",
                    "TDO" to "Torgau  Delitzsch  Oschatz, Sachsen",
                    "TE" to "TEcklenburg, Nordrhein-Westfalen",
                    "TET" to "TETerow, Mecklenburg-Vorpommern",
                    "TF" to "Teltow  Fläming, Brandenburg",
                    "TG" to "TorGau, Sachsen",
                    "THL" to "THüringer Landtag, Thüringen",
                    "THW" to "Technisches HilfsWerk, bundesweit",
                    "TIR" to "TIRschenreuth, Bayern",
                    "TO" to "Torgau  Oschatz, Sachsen",
                    "TÖL" to "TÖLz, Bayern",
                    "TP" to "TemPlin, Brandenburg",
                    "TR" to "TRier, Rheinland-Pfalz",
                    "TS" to "TraunStein, Bayern",
                    "TÜ" to "TÜbingen, Baden-Württemberg",
                    "TUT" to "TUTtlingen, Baden-Württemberg",
                    "UE" to "UElzen, Niedersachsen",
                    "UEM" to "UEckerMünde, Mecklenburg-Vorpommern",
                    "UFF" to "UFFenheim, Bayern",
                    "UH" to "Unstrut  Hainich, Thüringen",
                    "UL" to "ULm, Baden-Württemberg",
                    "UM" to "UckerMark, Brandenburg",
                    "UN" to "UNna, Nordrhein-Westfalen",
                    "USI" to "USIngen, Hessen",
                    "V" to "Vogtland, Sachsen",
                    "VAI" to "VAIhingen, Baden-Württemberg",
                    "VB" to "VogelsBerg, Hessen",
                    "VEC" to "VEChta, Niedersachsen",
                    "VER" to "VERden, Niedersachsen",
                    "VG" to "Vorpommern  Greifswald, Mecklenburg-Vorpommern",
                    "VIE" to "VIErsen, Nordrhein-Westfalen",
                    "VK" to "VölKlingen, Saarland",
                    "VOH" to "VOHenstrauß, Bayern",
                    "VR" to "Vorpommern  Rügen, Mecklenburg-Vorpommern",
                    "VS" to "Villingen-Schwenningen, Baden-Württemberg",
                    "W" to "Wuppertal, Nordrhein-Westfalen",
                    "WA" to "WAldeck, Hessen",
                    "WAF" to "WArendorF, Nordrhein-Westfalen",
                    "WAK" to "WArtburgKreis, Thüringen",
                    "WAN" to "WANne, Nordrhein-Westfalen",
                    "WAT" to "WATtenscheid, Nordrhein-Westfalen",
                    "WB" to "WittenBerg, Sachsen-Anhalt",
                    "WBS" to "WorBiS, Thüringen",
                    "WDA" to "WerDAu, Sachsen",
                    "WE" to "WEimar, Thüringen",
                    "WEL" to "WEiLburg, Hessen",
                    "WEN" to "WEideN, Bayern",
                    "WER" to "WERtingen, Bayern",
                    "WES" to "WESel, Nordrhein-Westfalen",
                    "WF" to "WolFenbüttel, Niedersachsen",
                    "WHV" to "WilhelmsHaVen, Niedersachsen",
                    "WI" to "WIesbaden, Hessen",
                    "WIL" to "WIttLich, Rheinland-Pfalz",
                    "WIS" to "WISmar, Mecklenburg-Vorpommern",
                    "WIT" to "WITten, Nordrhein-Westfalen",
                    "WIZ" to "WItZenhausen, Hessen",
                    "WK" to "WittstocK, Brandenburg",
                    "WL" to "Winsen (Luhe), Niedersachsen",
                    "WLG" to "WoLGast, Mecklenburg-Vorpommern",
                    "WM" to "WeilheiM, Bayern",
                    "WMS" to "WolMirStedt, Sachsen-Anhalt",
                    "WN" to "WaiblingeN, Baden-Württemberg",
                    "WND" to "WeNDel, Saarland",
                    "WO" to "WOrms, Rheinland-Pfalz",
                    "WOB" to "WOlfsBurg, Niedersachsen",
                    "WOH" to "WOlfHagen, Hessen",
                    "WOL" to "WOLfach, Baden-Württemberg",
                    "WOR" to "WOlfRatshausen, Bayern",
                    "WOS" to "WOlfStein, Bayern",
                    "WR" to "WernigeRode, Sachsen-Anhalt",
                    "WRN" to "WaReN, Mecklenburg-Vorpommern",
                    "WS" to "WasSerburg, Bayern",
                    "WSF" to "WeisSenFels, Sachsen-Anhalt",
                    "WST" to "WesterSTede, Niedersachsen",
                    "WSW" to "WeisSWasser, Sachsen",
                    "WT" to "WaldshuT, Baden-Württemberg",
                    "WTM" to "WitTMund, Niedersachsen",
                    "WÜ" to "WÜrzburg, Bayern",
                    "WUG" to "WeißenbUrG, Bayern",
                    "WÜM" to "WaldMÜnchen (mit einem Buchstabendreher), Bayern",
                    "WUN" to "WUNsiedel, Bayern",
                    "WUR" to "WURzen, Sachsen",
                    "WW" to "WesterWald, Rheinland-Pfalz",
                    "WZ" to "WetZlar, Hessen",
                    "WZL" to "WanZLeben, Sachsen-Anhalt",
                    "X" to "willkürlich gewählt, bundesweit",
                    "Y" to "Bundeswehr, bundesweit",
                    "Z" to "Zwickau, Sachsen",
                    "ZE" to "ZErbst, Sachsen-Anhalt",
                    "ZEL" to "ZELl, Rheinland-Pfalz",
                    "ZI" to "ZIttau, Sachsen",
                    "ZIG" to "ZIeGenhain, Hessen",
                    "ZP" to "ZschoPau, Sachsen",
                    "ZR" to "ZeulenRoda, Thüringen",
                    "ZW" to "ZWeibrücken, Rheinland-Pfalz",
                    "ZZ" to "ZeitZ, Sachsen-Anhalt"
            )
            //ausgabe.setText(kfzKennzeichen.get("H"))
            ausgabe.setText(kfzKennzeichen.getOrDefault(eingabeUser,defaultValue = "Das kenne ich nicht!"))

        }
    }
}